'\" t
.\" ident MRC HGU $Id$
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzBackground.3
.\" Date:       March 1999
.\" Author:     Richard Baldock
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz functions setting/getting background values.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH WlzBackground 3 "13th November 1996" "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzGetBackground, WlzSetBackground \- get and set the background value
of a woolz image object.
.SH SYNOPSIS
.nf
.sp
#include <Wlz.h>

WlzErrorNum WlzSetBackground(WlzObject	*obj,
			     WlzPixelV	bgd);

WlzPixelV WlzGetBackground(WlzObject	*obj);


.fi
.SH ARGUMENTS
.LP
.BI " " obj "		the image object pointer."
.BI " " bgd "		the background pixel value."
.LP
.SH MT-LEVEL
.LP
Unsafe
.SH DESCRIPTION
Procedures to get and set the background of a woolz object. The background
is a WlzPixelV structure and the grey-value type can be different to the
grey-value type of the grey-table. Both routines regard an empty object
as legal, WlzSetBackground does nothing and WlzGetBackground will return
a pixel value of zero. A domain-object must have a non-NULL domain and a
NULL domain is reported as an error. A NULL valuetable is legal and a zero
background value is assumed.
.LP
.I WlzSetBackground,
Set the background value to bgd. The new background will be of the same type
as bgd. On success WLZ_ERR_NONE is returned, error returns can be one of:
NULL_OBJECT, NULL_DOMAIN, INVALID_OBJECT_TYPE, INVALID_GREY_TYPE, 
INVALID_PLANEDOMAIN_TYPE, INVALID_VOXELTABLE_TYPE.
.I WlzGetBackground,
returns the background of the given object. On error the pixel type will be
WLZ_GREY_ERROR and the error can be obtained by calling WlzGetError or by
setting an error-handler. Possible errors are: NULL_OBJECT, NULL_DOMAIN,
INVALID_VALUETABLE_TYPE, INVALID_PLANEDOMAIN_TYPE, INVALID_VOXELTABLE_TYPE,
INVALID_OBJECT_TYPE.
.LP
The background value is passed or returned as a WlzPixelV structure:
.nf
.sp
typedef struct {
  WlzGreyType	type;
  WlzGreyV	v;
} WlzPixelV;
.fi
where type is one of WLZ_GREY_INT, WLZ_GREY_SHORT, WLZ_GREY_UBYTE, 
WLZ_GREY_FLOAT, WLZ_GREY_DOUBLE and v is a WlzGreyV union:
.nf
.sp
typedef union {
  int inv;
  short shv;
  UBYTE ubv;
  float flv;
  double dbv;
} WlzGreyV;
.fi

.SH EXAMPLES
.LP

.SH SEE ALSO
WlzGetError(3), WlzError(3)
.SH BUGS

