'\" te
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz							"
.\" Title:      WlzBoundingBox.3		                      	"
.\" Date:       March 1999
.\" Author:     Bill Hill 				    		"
.\" Copyright:	1999 Medical Research Council, UK.			"
.\"		All rights reserved.					"
.\" Address:	MRC Human Genetics Unit,				"
.\"		Western General Hospital,				"
.\"		Edinburgh, EH4 2XU, UK.					"
.\" Purpose:    Calculates the bounding box of a Woolz object.		"
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.	"
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzBoundingBox" 3 "%G%" "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzBoundingBox \- Calculates the bounding box.
.SH SYNOPSIS
.LP
.B #include <Wlz.h>
.LP
.BI "WlzIBox2 WlzBoundingBox2D(WlzObject *" "srcObj" ,
.in +4m
.BI "WlzErrorNum *" "dstErrNum" ");"
.in -4m
.LP
.BI "WlzIBox3 WlzBoundingBox3D(WlzObject *" "srcObj" ,
.in +4m
.br
.BI "WlzErrorNum *" "dstErrNum" ");"
.in -4m
.SH ARGUMENTS
.TS
tab(^);
lI l.
srcObj^source object pointer
binObjFlag^binary object flag
dstErrNum^destination pointer for error number, may be NULL
.TE
.SH MT-LEVEL
.LP
Safe
.SH DESCRIPTION
WlzBoundingBox2D and WlzBoundingBox3D calculate the bounding box of the
given Woolz object.
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf
/*
 * Simple example of using WlzBoundingBox3D() to caclulate the bounding
 * box of an object read from the standard input.
 */

#include <stdio.h>
#include <stdlib.h>
#include <Wlz.h>

int             main(char *argv[], int argc)
{
  WlzIBox3      bBox;
  WlzObject     *inObj = NULL;
  WlzErrorNum   errNum = WLZ_ERR_NONE;

  if((inObj= WlzReadObj(stdin, &errNum)) == NULL)
  {
    (void )fprintf(stderr, "%s: Failed to read input object.\n", *argv);
  }
  else
  {
    bBox = WlzBoundingBox3D(inObj, &errNum);
    WlzFreeObj(inObj);
    if(errNum == WLZ_ERR_NONE)
    {
      (void )printf("%d %d %d %d %d %d\n",
                    bBox.xMin, bBox.yMin, bBox.zMin,
                    bBox.xMax, bBox.yMax, bBox.zMax);
    }
    else
    {
      (void )fprintf(stderr,
                     "%s: Failed to calculate bounding box.\n",
                     *argv);
    }
  }
  return(errNum);
}
.fi
.cs R
.ps +2
.SH SEE ALSO
WlzBoundingBox(1), WlzError(3)
.SH BUGS
Still to be found.
