'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz							"
.\" Title:      WlzConvolve.3			                      	"
.\" Date:       March 1999	                                    	"
.\" Author:     Bill Hill 				    		"
.\" Copyright:	1999 Medical Research Council, UK.			"
.\"		All rights reserved.					"
.\" Address:	MRC Human Genetics Unit,				"
.\"		Western General Hospital,				"
.\"		Edinburgh, EH4 2XU, UK.					"
.\" Purpose:    Woolz function which space domain convolutions.		"
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.	"
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzConvolve" 3 "%G%" "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzConvolve \- Performs space-domain convolution.
.SH SYNOPSIS
.LP
.B #include <Wlz.h>
.LP
.BI "WlzObject *WlzConvolve(WlzObject *" "srcObj" ,
.BI "WlzConvolution *" "conv" ,
.ti +10m
.BI "int " "newObjFlag" ,
.BI "WlzErrorNum  *" wlzErr );
.LP
.BI "int WlzConvolveSeqParFn(WlzSeqParWSpace *" spWSpace ,
.BI "void *" "spData"
.ti +10m
.BI "WlzErrorNum  *" wlzErr );
.SH ARGUMENTS
.TS
tab(^);
lI l.
srcObj^source object pointer.
conv^convolution data structure
newObjFlag^new object or in\-place flag, non\-zero for a new object
spWSpace^WlzSeqPar workspace data structure
spData^used to pass \fIconv\fR through WlzSeqPar
wlzErr^destination error code pointer, may be null
.TE
.SH MT-LEVEL
.LP
Safe
.SH DESCRIPTION
WlzConvolve performs a space\-domain convolution on a
WLZ_2D_DOMAINOBJ object with integral (int, short or unsigned char)
grey values.
WlzConvolve returns a pointer to the convolved object or a NULL
pointer on error.
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf
/*
 * Simple example of using WlzConvolve() to perform a space
 * domain 3x3 mean convolution filter (See WlzSeqPar(3)).
 */

#include <stdio.h>
#include <stdlib.h>
#include <Wlz.h>

int             main(char *argv[], int argc)
{
  WlzObject     *inObj = NULL,
                *outObj = NULL;
  WlzErrorNum   errNum = WLZ_ERR_NONE;
  WlzConvolution conv;
  const int     meanMask[]
  {
    1, 1, 1,
    1, 1, 1,
    1, 1, 1
  };

  conv.type = WLZ_CONVOLVE_INT;
  conv.linkcount = 0;
  conv.xsize = 3;
  conv.ysize = 3;
  conv.cv = meanMask;
  conv.divscale = 9;
  sConv.offset = 0;
  sConv.modflag = 0;
  if((inObj= WlzReadObj(stdin, &errNum)) == NULL)
  {
    (void )fprintf(stderr, "%s: Failed to read input object.\n", *argv);
  }
  else if((outObj = WlzConvolveObj(inObj, &conv, 1, &errNum)) == NULL) ||
          (errNum != WLZ_ERR_NONE))
  {
    (void )fprintf(stderr, "%s: Failed to convolve object.\n", *argv);
  }
  else if((errNum = WlzWriteObj(stdout, outObj)) != WLZ_ERR_NONE)
  {
    (void )fprintf(stderr, "%s: Failed to write output object.\n", *argv);
  }
  return(errNum);
}
.fi
.cs R
.ps +2
.SH SEE ALSO
WlzSeqPar(3), WlzError(3)
.SH BUGS
Still to be found.
