.\" te
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz							"
.\" Title:      WlzCopy.3			                      	"
.\" Date:       November 1999	                                    	"
.\" Author:     Bill Hill 				    		"
.\" Copyright:	1999 Medical Research Council, UK.			"
.\"		All rights reserved.					"
.\" Address:	MRC Human Genetics Unit,				"
.\"		Western General Hospital,				"
.\"		Edinburgh, EH4 2XU, UK.					"
.\" Purpose:    Woolz functions for copying objects, domains, values	"
.\"		and properties.						"
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.	"
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.nh
.TH "WlzCopy" 3 "%G%" "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzCopy \- Woolz functions for copying objects, domains, values and properties.
.SH SYNOPSIS
.LP
.B #include <Wlz.h>
.LP
.BI "WlzObject *WlzCopyObject(WlzObject *" inObj ,
.in +4m
.br
.BI "WlzErrorNum *" wlzErr );
.in -4m
.LP
.BI "WlzDomain WlzCopyDomain(WlzObjectType " inObjType ,
.in +4m
.br
.BI "WlzDomain " inDom ,
.BI "WlzErrorNum *" wlzErr );
.in -4m
.LP
.BI "WlzValues WlzCopyValues(WlzObjectType " inObjType ,
.in +4m
.br
.BI "WlzValues " inVal ,
.BI "WlzDomain " inDom ,
.br
.BI "WlzErrorNum *" wlzErr );
.in -4m
.SH ARGUMENTS
.TS
tab(^);
lI l.
inObj^Woolz object to be copied.
inDom^Woolz domain to be copied, or for values to be
^copied.
inVal^Woolz values to be copied.
inObjType^Woolz object type of object to be copied, or
^parent object of values or domain to be copied.
wlzErr^Destination error code pointer, may be NULL.
.TE
.SH MT-LEVEL
.LP
Safe
.SH DESCRIPTION
.LP
.B WlzCopyObject
creates a new Woolz object which is a complete copy of
the given woolz object.
.LP
.B WlzCopyDomain
creates a new Woolz domain which is a complete copy of the
given domain. The given object type is used to determine
the domain type and may be the type of the domain's parent object.
.LP
.B WlzCopyValues
creates a new Woolz value table which is a complete copy of the
given values. The given object type is used to determine
the full type of the domain and values and may be the type of
the given value table's parent object.
The given domain is used to determine the region of the values
to be copied.
.SH EXAMPLES
.LP
.ps -2
.cs B 24
.cs R 24
.nf

/* Simple but useless example which reads a Woolz object
* from the standard input, copies it and then writes the
* copy to the standard output.
*/

#include <stdio.h>
#include <stdlib.h>
#include <Wlz.h>

int             main(char *argv[], int argc)
{
 WlzObject      *inObj = NULL,
                *outObj = NULL;
 WlzErrorNum   errNum = WLZ_ERR_NONE;

 if((inObj = WlzAssignObject(
             WlzReadObj(stdin,
                        &errNum), NULL)) == NULL)
 {
   (void )fprintf(stderr,
                  "%s: Failed to read object\\n",
                  *argv);
 }
 if(errNum == WLZ_ERR_NONE)
 {
   if((outObj = WlzCopyObject(inObj,
                              &errNum)) == NULL)
   {
     (void )fprintf(stderr,
                    "%s: Failed to copy object\\n",
                    *argv);
   }
 }
 if(inObj)
 {
   WlzFreeObj(inObj);
 }
 if(errNum == WLZ_ERR_NONE)
 {
   if((errNum = WlzWriteObj(stdout,
                            outObj)) != WLZ_ERR_NONE)
   {
     (void )fprintf(stderr,
                    "%s: Failed to write copied object\\n",
                    *argv);
   }
 }
 if(outObj)
 {
   WlzFreeObj(outObj);
 }
 return(errNum);
}

.fi
.cs R
.cs B
.ps +2
.SH SEE ALSO
WlzAffineTransform(3),
WlzError(3)
.SH BUGS
Still to be found.
