'\" t
.\" ident MRC HGU $Id$
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzDomainFill.3
.\" Date:       March 1999
.\" Author:     Richard Baldock
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz functions for filling holes in domains.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

.TH "WlzDomainFill" 3 "Sat Oct 18 15:17:08 1997" "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzDomainFill \- fill holes in a woolz domain object.
.SH SYNOPSIS
.nf
.sp
#include <Wlz.h>

WlzObject *WlzDomainFill(
  WlzObject	*obj,
  WlzErrorNum	*dstErr);


.fi
.SH ARGUMENTS
.LP
.BI " " obj "		object pointer."
.LP
.BI " " dstErr "	error pointer."
.LP
.SH MT-LEVEL
.LP
Safe
.SH DESCRIPTION
A procedure to fill "holes" in a woolz domain object
i.e. WLZ_2D_DOMAINOBJ or WLZ_3D_DOMAINOBJ. The 3D domain is filled
plane by plane.
.LP
.I *WlzDomainFill,
fills the domain of the input object by calculating the corresponding
boundary, discarding all internal ("down") boundaries and then
filling the resultant boundary. The returned object will have a NULL
valuetable. Possible errors are WLZ_ERR_OBJECT_NULL,
WLZ_ERR_DOMAIN_NULL, WLZ_ERR_OBJECT_TYPE, WLZ_ERR_DOMAIN_TYPE and
errors returned by WlzObjToBoundary(3) and WlzBoundToObj(3).

.SH EXAMPLES
.LP

.SH SEE ALSO
WlzError(3), WlzObjToBoundary(3) and WlzBoundToObj(3).
.SH BUGS

