'\" t
.\" ident MRC HGU $Id$
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzFileIO.3
.\" Date:       March 1999
.\" Author:     Richard Baldock
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz functions for file I/O.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH WlzFileIO 3 "22 Oct 1996" "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzReadObj, WlzWriteObj \- Routines to convert object structures to
 and from sequential data  streams, for input and output.
.SH SYNOPSIS
.LP
.B #include <Wlz.h>
.LP
.BI "WlzErrorNum WlzWriteObj(FILE *"fp, " WlzObject " "*obj" );
.LP
.BI "WlzObject *WlzReadObj(FILE *"fp, "WlzErrorNum *" ", dstErr")
.SH ARGUMENTS
.LP
.BI " " fp "		IO stream pointer as returned by fopen."
.LP
.BI " " obj "		object pointer.
.LP
.BI " " dstErr "        Destination erroe pointer, may be NULL.
.LP
.SH MT-LEVEL
.LP
Unsafe
.SH DESCRIPTION
.LP
.I WlzWriteObj,
writes object to file in sequential format and returns the number
of objects written..LP
.I WlzReadObj,
reads object in sequential format from file to structured object in core,
allocating space (see comments in documentation for WlzMakeSpace.c).
.SH SEE ALSO
WlzError(3), fopen(3)
.SH BUGS
Still to be found!
