'\" t
.\" ident MRC HGU $Id$
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzGreyRange.3
.\" Date:       March 1999
.\" Author:     Richard Baldock
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz functions for grey range query and manipulation.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH WlzGreyRange 3 "14th November 1996" "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzGreyRange \- grey-range query and manipulation procedures.
.SH SYNOPSIS
.nf
.sp
#include <Wlz.h>

WlzErrorNum WlzGreyRange(WlzObject	*obj,
			 WlzPixelV	*min,
			 WlzPixelV	*max)

.fi
.SH ARGUMENTS
.LP
.BI " " obj "		object pointer."
.BI " " min "		minimum pixel value return."
.BI " " max "		maximum pixel value return."
.LP
.SH MT-LEVEL
.LP
Unsafe
.SH DESCRIPTION
Routines for querying and setting the grey-value range of a woolz
object. The pixel returns will have the pixel type of the object
grey-value table. An empty object corresponds to a null operation.
.LP
.I WlzGreyRange,
calculates the grey-range of the given object. Possible errors are:
NULL_OBJECT, NULL_DOMAIN, NULL_VALUETABLE, INVALID_GREY_TYPE,
INVALID_VOXELTABLE_TYPE, INVALID_PLANEDOMAIN_TYPE,
INVALID_OBJECT_TYPE.

.SH EXAMPLES
.LP

.SH SEE ALSO
WlzError(3)
.SH BUGS

