'\" t
.\" ident MRC HGU $Id$
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzGetSectionFromObject.3
.\" Date:       March 1999
.\" Author:     Richard Baldock
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz functions to get a 2D section from a 3D object.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzGetSectionFromObject.3" 3 "Sun Feb 16 16:23:48 1997" "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzGetSectionFromObject \- get a 2D section from a 3D object.
.SH SYNOPSIS
.nf
.sp
#include <Wlz.h>

WlzObject *WlzGetSectionFromObject(
  WlzObject		*obj,
  WlzThreeDViewStruct	*viewStr);

.fi
.SH ARGUMENTS
.LP
.BI " " obj "		object pointer."
.LP
.BI " " viewStr "       3D view structure pointer."
.SH MT-LEVEL
.LP
Unsafe
.SH DESCRIPTION
Extract a 2D section from a 3D object as defined by the 3D view
structure pointer.
.LP
.I WlzGetSectionFromObject,
extracts the 2D section from the given 3D object. The object returned
will have the same grey-type as the given object including a pure
binary object. The section is defined by the viewing parameters
encoded in the view structure which is assumed to be initialised so
that the look-up tables are correct. The section returned will extend
to the edge of the reference object associated with the view-structure
which could be a subset of the given object. On error NULL is
returned.

The view structure can be created and initialised with
WlzMake3DViewStruct and WlzInit3DViewStruct.

.SH EXAMPLES
.LP

.SH SEE ALSO
WlzError(3), WlzMake3DViewStruct(3), WlzInit3DViewStruct(3).
.SH BUGS

