'\" t
.\" ident MRC HGU $Id$
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzIntervalScan.3
.\" Date:       March 1999
.\" Author:     Richard Baldock
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz functions for scaning an interval domain.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

.TH "WlzIntervalScan" 3 "Thu Nov 21 16:19:28 1996" "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzInitRasterScan, WlzNextInterval, WlzNextLine, WlzInitLineScan
\- procedures to scan an interval domain.
.SH SYNOPSIS
.nf
.sp
#include <Wlz.h>

WlzErrorNum 
WlzInitRasterScan(WlzObject 		*obj,
		  WlzIntervalWSpace 	*iwsp,
		  int 			raster)

int 
WlzNextInterval(WlzIntervalWSpace *iwsp)

WlzErrorNum 
WlzInitLineScan(WlzObject 		*obj,
		WlzIntervalWSpace	*iwsp,
		int 			raster,
		int 			step,
		int 			firstline)

int 
WlzNextLine(WlzIntervalWSpace *iwsp,
	    int step)

.fi
.SH ARGUMENTS
.LP
.BI " " obj "		object pointer."
.LP
.BI " " iwsp "          interval work space pointer."
.LP
.BI " " raster "	scanning direction control."
.LP
.BI " " step "          number of lines to step."
.LP
.BI " " firstline "     starting line."
.LP
.SH MT-LEVEL
.LP
Unsafe
.SH DESCRIPTION
Routines to traverse an interval  domain. See WlzGreyScan(3)
for coordinated traversing of grey tables.
.LP
Note  that  one  of   four   raster   directions   (up/down,
right/left)  may  be  specified.  Even  if raster is "left", pointers
are always preset  to  left  end  of  interval.  If "left",  then
rightmost  interval  in line first, otherwise leftmost interval.
.LP
.I WlzInitRasterScan,
initialises interval scanning with specified raster
direction. Directions are as follows:
.IP
.nf
.ta 1i 2i 3i
\fIraster       line numbers    column numbers\fR
.br
0       increasing      increasing
1       increasing      decreasing
2       decreasing      increasing
3       decreasing      decreasing
.fi
.LP
Note that even when decreasing column numbers are specified, all information
in workspace referring to an interval produced by, e.g.,
.I WlzNextGreyInterval(3),
refers to the interval end with
.B lowest
column number.
.LP
.I WlzNextInterval,
gets next interval in a standard object according to preset raster
direction.
Function has a return value of
.B 0
as each interval is returned, and
.B 1
when called beyond end of object.
The function will also return error code INVALID_DOMAIN_TYPE, although
this should not be possible if the scanning was initialised using
.I WlzInitRasterScan(3)
.LP
.I WlzInitLineScan,
similar to \fIWlzInitRasterScan\fR to initialise scanning from an
arbitrary line and arbitrary line step.
.LP
.I WlzNextLine,
similar to \fIWlzNextInterval\fR and used in conjuction with
\fIWlzInitLineScan\fR to scan line by line.

.SH EXAMPLES
.LP

.SH SEE ALSO
WlzError(3), WlzNextGreyInterval(3).
.SH BUGS

