'\" t
.\" ident MRC HGU $Id$
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzMorphologicalOps.3
.\" Date:       March 1999
.\" Author:     Richard Baldock
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz functions for morphological operations.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzMorphologicalOps" 3 "Jul 1997" "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzErosion, WlzDilation, WlzStructErosion, WlzStructDilation \-
Morphological operations for domain objects.
.SH SYNOPSIS
.nf
.sp
#include <Wlz.h>

WlzObject *WlzErosion(WlzObject 	*obj,
		      WlzConnectType 	connectivity);


.fi
.SH ARGUMENTS
.LP
.BI " " obj "		object pointer."
.LP
.BI " " connectivity "	connectivity type."
.LP
.SH MT-LEVEL
.LP
Unsafe
.SH DESCRIPTION
Morphological operations for application to woolz domain
objects. These apply to the domains only and are not grey-level
operations. For grey-level morphology see WlzGreyMorphologicalOps(3).
Objects can be 2D or 3D domain objects.
.LP
The \fBconnectivity\fR parameter defines the structuring element and
can have values: 
.nf
.sp
Value                   Structuring Element
-----                    -------------------
WLZ_4_CONNECTED         4-connected pixels, single plane
WLZ_8_CONNECTED         8-connected pixels, single plane
WLZ_6_CONNECTED         3D object - 6-connected pixels
                        2D object - 4-connected pixels
WLZ_18_CONNECTED        3D object - 18-connected pixels
                        2D object - 8-connected pixels
WLZ_26_CONNECTED        3D object - 26-connected pixels
                        2D object - 8-connected pixels
.sp
.fi
.LP
.I WlzErosion,
single pixel erosion using a structuring element defined by the
connectivity. If a 3D connectivity is applied to a 2D object then
4-connected erosion is assumed for WLZ_6_CONNECTED, 8-connected
otherwise. If a 2D connectivity is applied to a 3D object then it is
applied to each plane independently ie the 3D structuring element is
just a single plane.

.SH EXAMPLES
.LP

.SH SEE ALSO
WlzGreyMorphologicalOps(3), WlzError(3)
.SH BUGS

