'\" t
.\" ident MRC HGU $Id$
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzMorphometry.3
.\" Date:       March 1999
.\" Author:     Richard Baldock
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz functions to calculate morphometric measures.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH WlzMorphometry 3 "8th November, 1996" "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzArea, WlzVolume \- calculate morphometric measures on woolz objects.
.SH SYNOPSIS
These procedures will calculate a variety of shape and size measures on
woolz objects.
.nf
.sp
#include <Wlz.h>

int WlzArea(WlzObject *obj)

int WlzVolume(WlzObject	*obj)

.fi
.SH ARGUMENTS
.LP
.BI " " obj "		object pointer appropriate to each routine"
.LP
.SH MT-LEVEL
.LP
Unsafe
.SH DESCRIPTION
Each of these routines return the measurement value for the given woolz
object. In each case an impossible value is returned to indicate error.
.LP
.I WlzArea,
Calculate the area of a 2D domain object. Returns -1 on error with possible
errors: NULL_OBJECT, NULL_DOMAIN, INVALID_OBJECT_TYPE.
.LP
.I WlzVolume,
Calculate the pixel volume of a 3D domain object.
Returns -1 on error with possible
errors: NULL_OBJECT, NULL_DOMAIN, INVALID_OBJECT_TYPE, INVALID_DOMAIN_TYPE.
.LP
.SH EXAMPLES
.LP

.SH SEE ALSO
WlzError
.SH BUGS

