'\" te
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz							"
.\" Title:      WlzPrinicipalAngle.3		                      	"
.\" Date:       March 1999	                                    	"
.\" Author:     Bill Hill 				    		"
.\" Copyright:	1999 Medical Research Council, UK.			"
.\"		All rights reserved.					"
.\" Address:	MRC Human Genetics Unit,				"
.\"		Western General Hospital,				"
.\"		Edinburgh, EH4 2XU, UK.					"
.\" Purpose:    Calculates the centre of mass of a Woolz domain object.	"
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.	"
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzPrinicipalAngle" 3 "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzPrinicipalAngle \- Calculates centre of mass.
.SH SYNOPSIS
.LP
.B #include <Wlz.h>
.LP
.BI "double WlzPrinicipalAngle(WlzObject *" "srcObj" ,
.in +4m
.BI "WlzDVertex2 " "cMass" ,
.br
.BI "int " "binObjFlag" ,
.br
.BI "WlzErrorNum *" "wlzErr" ");"
.in -4m
.SH ARGUMENTS
.TS
tab(^);
lI l.
srcObj^source object pointer
cMass^center of mass of given object
binObjFlag^binary object flag
wlzErr^destination pointer for error number, may be NULL
.TE
.SH MT-LEVEL
.LP
Safe
.SH DESCRIPTION
WlzPrincipalAngle calculates the angle which the long principal axis
makes with the x-axis of the given object.
.sp 1
.EQ
theta = {1 over 2 }
        { tan sup -1 } ( 2 {I sub xy } over { { I sub yy - I sub xx } } )
.EN
.sp 1
where
.sp 1
.EQ
I sub xx = sum from x { sum from y {
           { { ( y - {c sub y } ) } sup 2 }
           G(x, y) } }
.EN
.sp 1
.EQ
I sub yy = sum from x { sum from y {
           { { ( x - {c sub x } ) } sup 2 }
           G(x, y) } }
.EN
.sp 1
.EQ
I sub xy = sum from x { sum from y {
           { ( x - {c sub x } ) ( y - {c sub y } ) }
           G(x, y) } }
.EN
.sp 1
and
.EQ
{c sub x }, {c sub y }
.EN
is the centre of mass.
.LP
The principal angle (
.EQ
theta
.EN
)
is returned in radians.
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf
/*
 * Simple example using WlzCentreOfMass2D() and WlzPrincipalAngle()
 * to caclulate the centre of mass and principal and of an object read
 * from the standard input.
 */

#include <stdio.h>
#include <stdlib.h>
#include <Wlz.h>

int             main(char *argv[], int argc)
{
  double        pAngle;
  WlzDVertex2   cOfMass;
  WlzObject     *inObj = NULL;
  WlzErrorNum   errNum = WLZ_ERR_NONE;

  if((inObj= WlzReadObj(stdin, &errNum)) == NULL)
  {
    (void )fprintf(stderr, "%s: Failed to read input object.\n", *argv);
  }
  else
  {
    cOfMass = WlzCentreOfMass2D(inObj, 0, NULL, &errNum);
    if(errNum == WLZ_ERR_NONE)
    {
      pAngle = WlzPrincipalAngle(inObj, cOfMass, 0, &errNum);
      if(errNum != WLZ_ERR_NONE)
      {
        (void )fprintf(stderr,
                       "%s: Failed to compute principal angle.\n",
                       *argv);
      }
    }
    else
    {
      (void )fprintf(stderr,
                     "%s: Failed to compute centre of mass.\n",
                     *argv);
    }
    WlzFreeObj(inObj);
  }
  if(errNum == WLZ_ERR_NONE)
  {
    (void )ptintf("%g %g %g\n",
                  cOfMass3D.vtX, cOfMass3D.vtY, cOfMass3D.vtZ);
  }
  return(errNum);
}
.fi
.cs R
.ps +2
.SH SEE ALSO
WlzPrincipalAngle(1), WlzCentreOfMass(3), WlzError(3)
.SH BUGS
Still to be found.
