'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz							"
.\" Title:      WlzSampleObj.3			                      	"
.\" Date:       April 1999	                                    	"
.\" Author:     Bill Hill 				    		"
.\" Copyright:	1999 Medical Research Council, UK.			"
.\"		All rights reserved.					"
.\" Address:	MRC Human Genetics Unit,				"
.\"		Western General Hospital,				"
.\"		Edinburgh, EH4 2XU, UK.					"
.\" Purpose:    Woolz function which implements a sub-sampling filter   "
.\"    		with point, mean and gaussian sub-sampling kernels.	"
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.	"
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzSampleObj" 3 "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzSampleObj \- Performs sub\-sampling.
.SH SYNOPSIS
.LP
.B #include <Wlz.h>
.LP
.BI "WlzObject *WlzSampleObj(WlzObject *" "srcObj" ,
.in +4m
.br
.BI "WlzIVertex2 " "samFac" ,
.BI "WlzSampleFn " "samFn" ,
.br
.BI "WlzErrorNum *" "wlzErr" );
.in -4m
.SH ARGUMENTS
.TS
tab(^);
lI l.
srcObj^source object pointer.
^Only WLZ_EMPTY_OBJ and WLZ_2D_DOMAINOBJ object types are
^valid. WLZ_2D_DOMAINOBJ objects must also have grey values.
samFac^sampling factor for both rows and columns.
^The sampling factor has independent horizontal and vertical
^components which are the reciprocal of the scale components.
samFn^the sampling function specifies the convolution kernel
^used for sub\-sampling and can be one of: WLZ_SAMPLEFN_POINT,
^WLZ_SAMPLEFN_GAUSS, WLZ_SAMPLEFN_MEAN, WLZ_SAMPLEFN_MIN,
^WLZ_SAMPLEFN_MAX or WLZ_SAMPLEFN_MEDIAN which specify point,
^gaussian, mean, min, max and median convolution kernels
^respectively.
wlzErr^destination pointer for the Woolz error number
^which may be NULL if not required.
.TE
.SH MT-LEVEL
.LP
Safe
.SH DESCRIPTION
WlzSampleObj sub\-samples the given object using the given sampling
factor, sampling method.
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf
/*
 * Simple example of using WlzSampleObj().
 * Applies a scale transformation of of 0.5  to the Woolz object
 * read from the standard input and then writes the sub-sampled
 * object to the standard output.
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <Wlz.h>

int             main(char *argv[], int argc)
{
  WlzObject     *inObj = NULL,
                *outObj = NULL;
  WlzIVertex2    samFac;
  WlzSampleFn   samFn;
  WlzErrorNum   errNum = WLZ_ERR_NONE;

  samFac.vtX = 2;
  samFac.vtY = 2;
  samFac = WLZ_SAMPLEFN_GAUSS;
  if((inObj= WlzReadObj(stdin, &errNum)) == NULL)
  {
    (void )fprintf(stderr, "%s: Failed to read input object.\n", *argv);
  }
  else if((outObj = WlzSampleObj(inObj, samFac, samFn,
                                   &errNum)) == NULL) ||
          (errNum != WLZ_ERR_NONE))
  {
    (void )fprintf(stderr, "%s: Failed to sub-sample object.\n", *argv);
  }
  else if((errNum = WlzWriteObj(stdout, outObj)) != WLZ_ERR_NONE)
  {
    (void )fprintf(stderr, "%s: Failed to write output object.\n", *argv);
  }
  return(errNum);
}
.fi
.cs R
.ps +2
.SH SEE ALSO
WlzError(3)
.SH BUGS
Still to be found.
