'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzSobel.3
.\" Date:       March 1999
.\" Author:     Bill Hill
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz function which implements a Sobel edge detection
.\"		filter.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzSobel" 3 "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzSobel \- Performs Sobel edge detection.
.SH SYNOPSIS
.LP
.B #include <Wlz.h>
.LP
.BI "WlzObject *WlzSobel(WlzObject *" "srcObj" ,
.BI "int " "hFlag" ,
.BI "int " "vFlag" ,
.BI "WlzErrorNum *" wlzErr );
.SH ARGUMENTS
.TS
tab(^);
lI l.
srcObj^source object pointer.
hFlag^applies horizontal edge kernel if non\-zero
vFlag^applies vertical edge kernel if non\-zero
wlzErr^destination error code pointer, may be NULL
.TE
.SH MT-LEVEL
.LP
Safe
.SH DESCRIPTION
WlzSobel applies a 3X3 Sobel edge detection filter to a
WLZ_2D_DOMAINOBJ object with integral (int, short or unsigned char)
grey values.
WlzSobel returns a pointer to the convolved object or a NULL
pointer on error.
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf
/*
 * Simple example of using WlzSobel() to perform edge detection
 */

#include <stdio.h>
#include <stdlib.h>
#include <Wlz.h>

int             main(char *argv[], int argc)
{
  WlzObject     *inObj = NULL,
                *outObj = NULL;
  WlzErrorNum   errNum = WLZ_ERR_NONE;

  if((inObj= WlzReadObj(stdin, &errNum)) == NULL)
  {
    (void )fprintf(stderr, "%s: Failed to read input object.\\n", *argv);
  }
  else if((outObj = WlzSobel(inObj, 1, 1, &errNum)) == NULL) ||
          (errNum != WLZ_ERR_NONE))
  {
    (void )fprintf(stderr, "%s: Failed to convolve object.\\n", *argv);
  }
  else if((errNum = WlzWriteObj(stdout, outObj)) != WLZ_ERR_NONE)
  {
    (void )fprintf(stderr, "%s: Failed to write output object.\\n", *argv);
  }
  return(errNum);
}
.fi
.cs R
.ps +2
.SH SEE ALSO
WlzConvolve(3), WlzSeqPar(3), WlzError(3)
.SH BUGS
Still to be found.
