'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzAffineTransformLSq.1
.\" Date:       March 1999
.\" Author:     Bill Hill
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Computes an affine transform from a list of verticies
.\"		and vertex displacements.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzAffineTransformLSq" 1 "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzAffineTransformLSq \- Computes an affine transform from a list of verticies
and vertex displacements.
.SH SYNOPSIS
.LP
.BI "WlzAffineTransformLSq [ -o" "<output object file>" "]"
.in +4m
.br
.BI "[-a] [-r] [-t] [-h] [" "<input data file>" "]"
.in -4m
.SH OPTIONS
.TS
tab(^);
lb l.
\-a^Compute 2D affine transform.
\-h^Help, prints a usage message.
\-o^Output object file name.
\-r^Compute 2D registration transform, affine
^but no scale or shear.
\-t^Compute 2D translation transform.
.TE
By default the input data are read from the standard input
and the affine transform object is written to the standard output.
.SH DESCRIPTION
WlzAffineTransformLSq computes an affine transform from the given
list of verticies and thier displacements.
.LP
The input data must have records with the format:
.TS
tab(^);
l l l l.
<\fIvertex x\fR>^<\fIvertex y\fR>^<\fIdisplacement x\fR>^<\fIdisplacement y\fR>
.TE
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf

cat tst.num
   1.0  1.0  2.1  1.0
   2.0  1.0  1.0  0.1
   2.0  2.0  2.1 -1.0

WlzAffineTransformLSq tst.num | WlzFacts
   Object type: WLZ_AFFINE_TRANS.
     Linkcount: 0.
     Transform type: WLZ_TRANSFORM_2D_AFFINE.
     Linkcount: 1.
     tx: 2.1.
     ty: 3.
     tz: 0.
     scale: 1.
     theta: -1.5708.
     phi: 0.
     alpha: 0.2.
     psi: 0.785398.
     xsi: 0.
     invert: 0.

WlzAffineTransformLSq -r tst.num | WlzFacts
   Object type: WLZ_AFFINE_TRANS.
     Linkcount: 0.
     Transform type: WLZ_TRANSFORM_2D_AFFINE.
     Linkcount: 1.
     tx: 2.15156.
     ty: 3.09784.
     tz: 0.
     scale: 1.
     theta: -1.62075.
     phi: 0.
     alpha: 0.
     psi: 0.
     xsi: 0.
     invert: 0.

WlzAffineTransformLSq -t tst.num | WlzFacts
   Object type: WLZ_AFFINE_TRANS.
     Linkcount: 0.
     Transform type: WLZ_TRANSFORM_2D_AFFINE.
     Linkcount: 1.
     tx: 1.73333.
     ty: 0.0333333.
     tz: 0.
     scale: 1.
     theta: 0.
     phi: 0.
     alpha: 0.
     psi: 0.
     xsi: 0.
     invert: 0.

.fi
.cs R
.ps +2
.SH SEE ALSO
WlzAffineTransformLSq(3).
.SH BUGS
Still to be found.
