'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzExplode.1
.\" Date:       March 1999
.\" Author:     Bill Hill
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz binary which explodes a 3D domain object into
.\"		2D domain objects.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzExplode" 1 "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzExplode \- Explodes a Woolz 3D domain object or a compound object into 2D domain objects.
.SH SYNOPSIS
.LP
.BI "WlzExplode [ -b" "<file body>" "] [-e" "<file extension>" "] [-h]"
.in +4m
.br
.BI [ "<input object file>" ]
.in -4m
.SH OPTIONS
.TS
tab(^);
lb l.
\-b^output object file body.
\-e^output object file extension (default wlz).
\-h^Help, prints usage message.
.TE
By default the input object is read from the standard input
and the output objects are written to the standard output.
.SH DESCRIPTION
Explodes a WLZ_3D_DOMAINOBJ or WLZ_COMPOUND_ARR_1
object into WLZ_2D_DOMAINOBJ objects.
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf

# An example using WlzExplode explode a 3D object into a series of
# 2D object files. If lobster.wlz has plane coordinates from 7 to 36
# then 30 output files will be created with file names:
#   lobsterPlane000007.wlz, ..., lobsterPlane000036.wlz

WlzExplode -b lobsterPlane lobster.wlz

# A simple example in which a 3D object is read from the standard input
# exploded and the 2D objects concatonated to the standard output.

WlzExplode <infile3D.wlz >outfile2D.wlz

.fi
.cs R
.ps +2
.SH SEE ALSO
WlzConstruct(1), WlzExplode(3).
.SH BUGS
Still to be found.
