'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzGreyCrossing.1
.\" Date:       March 1999
.\" Author:     Bill Hill
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz binary which detects grey value crossings in an
.\"		integral 2D domain object.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzGreyCrossing" 1 "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzGreyCrossing \- Detects grey value crossings
.SH SYNOPSIS
.LP
.BI "WlzGreyCrossing [ -o" "<output object file>" "]"
.BI "[-c " "crossing value" "]"
.in +4m
.br
.br
.BI "[-h] [" "<input object file>" ]
.in -4m
.SH OPTIONS
.TS
tab(^);
lb l.
\-o^output object file name.
\-c^grey crossing value, default 0.
\-h^Help, prints usage message.
.TE
By default the input object is read from the standard input
and the output object is written to the standard output.
Unless the
.SH DESCRIPTION
Computes a grey value crossing image from a 2D domain object with
integral grey values.
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf

# An example using WlzLaplacian(1) and WlzGreyCrossing for edge
# detection

WlzPixConvert 1 <infile.wlz | \\
WlzLaplacian | \\
WlzGreyCrossing -c0 | \\
WlzThreshold -H -v1 >outfile.wlz

.fi
.cs R
.ps +2
.SH SEE ALSO
WlzGreyCrossing(3).
.SH BUGS
Still to be found.
