'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzHistogramMatchObj.1
.\" Date:       March 1999
.\" Author:     Bill Hill
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz binary which histogram matches a Woolz domain
.\"		object.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzHistogramMatchObj" 1 "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzHistogramMatchObj \- Histogram matches a Woolz domain object.
.SH SYNOPSIS
.LP
.BI "WlzHistogramMatchObj  -m" "<target> "
.in +4m
.br
.BI "[ -o" "<output object file>" "] [-h]"
.br
.BI "[-s" "<smoothing>" "]"
.BI "[-t" "<smoothing>" "]"
.br
.BI "[-i] [-d" "<min>,<max>" "]"
.BI [ "<input object file>" ]
.in -4m
.SH OPTIONS
.TS
tab(^);
lb l.
\-m^target histogram object file.
\-o^output object file.
\-h^help, prints usage message.
\-s^input object histogram smoothing.
\-t^target histogram smoothing.
\-i^independent planes.
\-d^histogram distance range.
.TE
By default the input object is read from the standard input
and the output object  is written to the standard output.
.LP
The histogram distance range limits
are comma separated and default to 0.0,1.0.
.LP
If a histogram distance range is given,
then only the domain objects/planes
which have a histogram within 
that distance range from the target histogram
are matched.
.SH DESCRIPTION
Modifies the grey values of the input object
so that the histogram of the modified object's grey values
matches the target histogram.
.LP
The smoothing factor is the low\-pass gaussian convolution
kernel half\-height full\-width in bins
(default 0), used to smooth the histogram(s)
before matching.
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf

# An example which uses WlzHistogramMatchObj and WlzHistogramObj to
# match the histogram of one domain object to another.
# an object.

WlzHistogramObj refObj.wlz | \\
WlzHistogramMatchObj -m - -o matchedObj.wlz myObj.wlz

# An example which uses WlzHistogramMatchObj to match all planes of
# a 3D image to plane 100.

WlzClipObjToBox -z 100,100 my3Dobj.wlz| \\
WlzHistogramObj - | \\
WlzHistogramMatchObj -m - -o matched3DObj.wlz my3Dobj.wlz

.fi
.cs R
.ps +2
.SH SEE ALSO
WlzHistogramObj(1),
WlzHistogramDistance(1),
WlzHistogram(3).
.SH BUGS
Still to be found.
