'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzHistogramRebin.1
.\" Date:       March 1999
.\" Author:     Bill Hill
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz binary which re-bins a Woolz histogram object.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzHistogramRebin" 1 "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzHistogramRebin \- Re\-bins a Woolz histogram object.
.SH SYNOPSIS
.LP
.BI "WlzHistogramRebin [ -o" "<output object file>" "] [-a] [-h]"
.in +4m
.br
.BI "[-i] [-f] [-n" "<bins>" "] [-s" "<start>" "] [-w" "<width>" "]"
.br
.BI [ "<input object file>" ]
.in -4m
.SH OPTIONS
.TS
tab(^);
lb l.
\-o^output file name.
\-a^output the histogram as ascii data not a Woolz histogram
^object.
\-h^help, prints usage message.
\-i^create integer bin values.
\-f^create (double precision) floating point bin values.
\-n^number of histogram bins.
\-s^start value, lower limit of histogram.
\-w^width of the histogram bins.
.TE
By default the input histogram object is read from the standard input
and the output histogram data/object  is written to the standard output.
The default number of bins, origin and bin width values are those of the
input histogram object.
.SH DESCRIPTION
Re\-bins a Woolz histogram object as required.
.LP
Output ascii data are written as a set of records one per line,
with each record composed of two fields separated by white space
characters:
.sp 1
.in +4m
.TS
tab(^);
l l.
<grey value>^<histogram bin occupancy>
.TE
.in -4m
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf

# An example which uses WlzHistogramRebin and xgraph to plot a
# histogram with 256 bins, starting at 0 and with a bin width
# of 1.

WlzHistogramRebin -a -s0 -n256 -w1 myHist.wlz | xgraph

.fi
.cs R
.ps +2
.SH SEE ALSO
WlzHistogram(3).
.SH BUGS
Still to be found.
