'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzHistogramObj.1
.\" Date:       March 1999
.\" Author:     Bill Hill
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz binary which computes a Woolz histogram object
.\"		from a 2D or 3D domain object.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzHistogramObj" 1 "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzHistogramObj \- Computes a Woolz histogram object from a 2D or 3D domain
object.
.SH SYNOPSIS
.LP
.BI "WlzHistogramObj [ -o" "<output object file>" "] [-a] [-h]"
.in +4m
.br
.BI "[-n" "<bins>" "] [-s" "<start>" "] [-w" "<width>" "]"
.br
.BI [ "<input object file>" ]
.in -4m
.SH OPTIONS
.TS
tab(^);
lb l.
\-o^output file name.
\-a^output the histogram as ascii data not a Woolz histogram
^object.
\-h^Help, prints usage message.
\-n^number of histogram bins.
\-s^start value, lower limit of histogram.
\-w^width of the histogram bins.
.TE
By default the input object is read from the standard input
and the output histogram data/object  is written to the standard output.
If the number of histogram bins is not specified then
the number of bins, the origin and the bin width
are computed as follows:
.br
.in +4m
.TS
tab(^);
l l l.
number of bins ^ = ^ ceil(max(g) - min(g) + 1.0)
start value ^ = ^ min(g)
bin width ^ = ^ 1.0
.TE
.in -4m
where max(g) and min(g) are the maximum and minimum grey values in
the domain object.
.SH DESCRIPTION
Computes a Woolz histogram object from the input Woolz 2D or 3D domain
object.
.LP
Output ascii data are written as a set of records one per line,
with each record composed of two fields separated by white space
characters:
.sp 1
.in +4m
.TS
tab(^);
l l.
<grey value>^<histogram bin occupancy>
.TE
.in -4m
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf

# An example which uses WlzHistogramObj and xgraph to plot the
# histogram of a domain object.

WlzHistogramObj -a myObj.wlz | xgraph

.fi
.cs R
.ps +2
.SH SEE ALSO
WlzHistogram(3).
.SH BUGS
Still to be found.
