'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzHistogramEqualiseObj.1
.\" Date:       March 1999
.\" Author:     Bill Hill
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz binary which histogram equalises Woolz domain
.\"		object.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzHistogramEqualiseObj" 1 "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzHistogramEqualiseObj \- Histogram equalises a Woolz domain object.
.SH SYNOPSIS
.LP
.BI "WlzHistogramEqualiseObj [ -o" "<output object file>" "] [-h]"
.in +4m
.br
.B "[-D]"
.BI "[-s" "<smoothing>" "]"
.BI [ "<input object file>" ]
.in -4m
.SH OPTIONS
.TS
tab(^);
lb l.
\-D^dither pixel values when mapping.
\-o^output object file.
\-h^help, prints usage message.
\-s^histogram smoothing factor.
.TE
By default the input object is read from the standard input
and the output object  is written to the standard output.
.SH DESCRIPTION
Histogram equalises the given Woolz domain object so that the
histogram of the modified object's grey values approximates
a uniform histogram.
.LP
The smoothing factor is the low\-pass gaussian convolution
kernel half\-height full\-width in bins
(default 0), used to smooth the objects histogram 
before equalisation.
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf

# An example which uses WlzHistogramEqualiseObj to histogram equalise
# an object.

WlzHistogramEqualiseObj myObj.wlz >myEqualisedObj.wlz

.fi
.cs R
.ps +2
.SH SEE ALSO
WlzHistogram(3).
.SH BUGS
Still to be found.
