'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzHistogramSmooth.1
.\" Date:       March 1999
.\" Author:     Bill Hill
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz binary which low-pass filters a Woolz histogram
*		object.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzHistogramSmooth" 1 "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzHistogramSmooth \- Low\-pass filters a Woolz histogram object.
.SH SYNOPSIS
.LP
.BI "WlzHistogramSmooth [ -o" "<output object file>" "] [-a] [-h]"
.in +4m
.br
.BI "[-s" "<smoothing>" "]
.BI [ "<input object file>" ]
.in -4m
.SH OPTIONS
.TS
tab(^);
lb l.
\-o^output file name.
\-a^output the histogram as ascii data not a Woolz histogram
^object.
\-h^help, prints usage message.
\-s^smoothing factor.
.TE
By default the input histogram object is read from the standard input
and the output histogram data/object  is written to the standard output.
.LP
The smoothing factor is the gaussian kernel half\-height full\-width
in bins (default 1).
.SH DESCRIPTION
Smooths a Woolz histogram object by convolving the histogram bins with a
gaussian.
.LP
Output ascii data are written as a set of records one per line,
with each record composed of two fields separated by white space
characters:
.sp 1
.in +4m
.TS
tab(^);
l l.
<grey value>^<histogram bin occupancy>
.TE
.in -4m
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf

# An example which uses WlzHistogramSmooth and xgraph to plot a
# smoothed histogram.

WlzHistogramSmooth -a -s5 myHist.wlz | xgraph

.fi
.cs R
.ps +2
.SH SEE ALSO
WlzHistogram(3).
.SH BUGS
Still to be found.
