'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzMorphological.1
.\" Date:       March 1999
.\" Author:     Richard Baldock
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz filters applying morphological operations.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzMorphological" 3 "Sat Aug 16 15:11:35 1997" "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzErosion \- Woolz filters applying morphological operations to domain objects.
.SH SYNOPSIS
.nf
.sp
WlzErosion [-c<n>] [-h] [input file]

.fi
.SH OPTIONS
.TS
tab(^);
lb l.
\-c4^4-connected erosion(2D)
\-c8^8-connected erosion(2D)
\-c6^6-connected erosion(3D)
\-c18^18-connected erosion(3D)
\-c26^26-connected erosion(3D)
\-h^Help, prints usage message.
.TE
By default the input object is read from the standard input
and the output is written to the standard output.
.SH DESCRIPTION
WlzErosion erodes the input object using a structuring element defined
by the given connectivity. If a 2D connectivity is applied to a 3D
object then each plane is eroded independently.
.LP

.SH EXAMPLES
.LP

.SH SEE ALSO

.SH BUGS

