'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzPrinicipalAngle.1
.\" Date:       March 1999
.\" Author:     Bill Hill
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz binary which calculates the mass and centre of
.\"		mass of domain objects.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzPrinicipalAngle" 1 "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzPrinicipalAngle \- Calculates the mass and centre of
mass and principal angle of domain objects.
.SH SYNOPSIS
.LP
.BI "WlzPrinicipalAngle [ -o" "<output file>" "] [-b] [-d] [-h]"
.in +4m
.br
.BI [ "<input object file>" ]
.in -4m
.SH OPTIONS
.TS
tab(^);
lb l.
\-o^output file name.
\-b^object is considered a binary object.
\-d^output angle in degrees instead of radians.
\-h^Help, prints usage message.
.TE
By default the input object is read from the standard input
and the output is written to the standard output.
.SH DESCRIPTION
WlzPrinicipalAngle calculates the mass, centre of mass
and principal angle
of the input Woolz 2D
domain object.
The mass, centre of mass 
and principal angle are written to the output
file in the following order:
.br
<mass> <x> <y> <angle>
.br
Where x and y are the column and line coordinates of the
centre of mass.
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf

# WlzPrinicipalAngle reads an object from myobj.wlz, calculates
# its mass,  centre of mass and principal angle then prints them
# to the standard output (angle in degrees).

WlzPrinicipalAngle -d myobj.wlz

.fi
.cs R
.ps +2
.SH SEE ALSO
WlzPrinicipalAngle(3).
.SH BUGS
Still to be found.
