'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzSampleObj.1
.\" Date:       March 1999
.\" Author:     Bill Hill
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz binary which sub-samples Woolz objects.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzSampleObj" 1 "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzSampleObj \- Sub-samples Woolz 2D domain objects objects.
.SH SYNOPSIS
.LP
.BI "WlzSampleObj [ -o" "<output object file>" "]"
.in +4m
.br
.BI  "[-x" "<column sampling factor>" "]"
.br
.BI  "[-y" "<line sampling factor>" "]"
.br
.BI  "[-z" "<plane sampling factor>" "]"
.br
.BI  "[-a]"
.BI  "[-e]"
.BI  "[-i]"
.BI  "[-g]"
.BI  "[-m]"
.BI  "[-p]"
.BI  "[-h]"
.BI [ "<input object file>" ]
.in -4m
.SH OPTIONS
.TS
tab(^);
lb l.
\-o^output object file name.
\-x^column sub\-sampling factor.
\-y^line sub\-sampling factor.
\-y^plane sub\-sampling factor.
\-a^maximum value convolution kernel.
\-e^median value convolution kernel.
\-i^minimum value convolution kernel.
\-g^gaussian convolution kernel.
\-m^mean convolution kernel.
\-p^point sampling.
\-h^Help, prints usage message.
.TE
By default the input object is read from the standard input
and the output object is written to the standard output.
.SH DESCRIPTION
Sub-samples a woolz interval domain object with grey values.
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf

# An example of using WlzSampleObj to apply a scale transform
# (scale = 0.5) using point sampling:

WlzSampleObj -x 2 -y 2 -p <infile.wlz > outfile.wlz

# Sub-sampling an object using a gaussian convolution kernel
# with scale along rows = 0.3333 and the scale down columns
# 0.5.

WlzSobel -x 3 -y 2 -g -o outfile.wlz infile.wlz

.fi
.cs R
.ps +2
.SH SEE ALSO
WlzSampleObj(3).
.SH BUGS
Still to be found.
