'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzSobel.1
.\" Date:       March 1999
.\" Author:     Bill Hill
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz binary which applies a Sobel edge detection
.\"		filter to a 2D domain object.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzSobel" 1 "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzSobel \- Applies a 3X3 Sobel edge detection filter.
.SH SYNOPSIS
.LP
.BI "WlzSobel [ -o" "<output object file>" "] [-x] [-y] [-h]"
.in +4m
.br
.BI [ "<input object file>" ]
.in -4m
.SH OPTIONS
.TS
tab(^);
lb l.
\-o^output object file name.
\-x^no horizontal pass.
\-y^no vertical pass.
\-h^Help, prints usage message.
.TE
By default the input object is read from the standard input
and the output object is written to the standard output.
.SH DESCRIPTION
Applies a 3X3 Sobel edge detection filter to the input Woolz object,
which must be a WLZ_2D_DOMAINOBJ with integral
(int, short or unsigned char) grey values.
.SH EXAMPLES
.LP
.ps -2
.cs R 24
.nf

# An example of using WlzSobel to detect only vertical edges.

WlzSobel -o outfile.wlz -x infile.wlz

# A simple example in which both horizontal and vertical edges
# are detected.

WlzSobel <infile.wlz >outfile.wlz

.fi
.cs R
.ps +2
.SH SEE ALSO
WlzSobel(3).
.SH BUGS
Still to be found.
