'\" t
.\" ident MRC HGU $Id$
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Project:    Woolz
.\" Title:      WlzTransposePlanes.1
.\" Date:       July 2000
.\" Author:     Richard Baldock
.\" Copyright:	1999 Medical Research Council, UK.
.\"		All rights reserved.
.\" Address:	MRC Human Genetics Unit,
.\"		Western General Hospital,
.\"		Edinburgh, EH4 2XU, UK.
.\" Purpose:    Woolz binary which transposes the planes of a 3D woolz object.
.\" $Revision$
.\" Maintenance:Log changes below, with most recent at top of list.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH "WlzTransposePlanes" 1 "MRC HGU Woolz" "Woolz Procedure Library"
.SH NAME
WlzTransposePlanes \- Transpose the planes of 3D Woolz objects.
.SH SYNOPSIS
.LP
.BI "WlzTransposePlanes"
.in +4m
.br
.BI  "[-o" "<offset>" "]"
.br
.BI  "[-h]"
.br
.BI  "[-v]"
.BI [ "<input object file>" ]
.in -4m
.SH OPTIONS
.TS
tab(^);
lb l.
\-o^offset for transpose.
\-h^Help, prints usage message.
\-v^Verbose operation.
.TE
.LP
By default the input object is read from the standard input
and the output object is written to the standard output.
.SH DESCRIPTION
Transpose the planes of a 3D woolz object. The transpose relation is
new-plane = offset - old-plane. This is equivalent to reflection about 
the X-Y plane through offset/2. By default the offset is the sum of
the first and last planes of the input object.

.SH EXAMPLES
.LP 
.ps -2
.cs R 24
.nf

# The following command transposes the planes of the object leaving
# the first and last planes unchanged.

WlzTransposePlanes  infile.wlz > outfile.wlz


# The following command transposes the planes of the object relecting
# the object about the origin

WlzTransposePlanes  -o0 infile.wlz > outfile.wlz

.fi 
.cs R
.ps +2

.SH SEE ALSO

.SH BUGS
Still to be found.
